language: python

python:
  - "3.4"
  - "2.7"
  - "pypy"

env:
  - "$DJANGO_DRF='django<1.8' 'djangorestframework<3'"
  - "$DJANGO_DRF='djangorestframework>=3'"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO_DRF
  - pip install -r requirements-dev.txt
  - pip freeze

# command to run tests, e.g. python setup.py test
script: make check
